Here's the `-Ytyper-debug` trace for `failed`:
```
|    |    |-- o.next.get.next.get : pt=Test.Owned[Test.Owner.type] EXPRmode (site: method fails in Test2)
|    |    |    |-- o.next.get.next EXPRmode-POLYmode-QUALmode (site: method fails in Test2)
|    |    |    |    |-- o.next.get EXPRmode-POLYmode-QUALmode (site: method fails in Test2)
|    |    |    |    |    |-- o.next EXPRmode-POLYmode-QUALmode (site: method fails in Test2)
|    |    |    |    |    |    |-- o EXPRmode-POLYmode-QUALmode (site: method fails in Test2)
|    |    |    |    |    |    |    \-> o.type (with underlying type Test.Owned[Test.Owner.type])
|    |    |    |    |    |    \-> o.next.type (with underlying type Option[_2.R.Type forSome { val _2: Test.Owner.type }])
|    |    |    |    |    \-> _2.R.Type
|    |    |    |    \-> Option[_2.R.Type forSome { val _2: P }]
|    |    |    [search #1] start `=> A`, searching for adaptation to pt=_2.R.Type => Test.Owned[Test.Owner.type] (silent: method fails in Test2) implicits disabled
|    |    |    [search #2] start `=> A`, searching for adaptation to pt=(=> _2.R.Type) => Test.Owned[Test.Owner.type] (silent: method fails in Test2) implicits disabled
sandbox/test2.scala:3: error: type mismatch;
 found   : _2.R.Type where val _2: P
 required: Test.Owned[Test.Owner.type]
  def fails(o: Owned[Owner.type]): Owned[Owner.type] = o.next.get.next.get
```

This might well be the same bug as scala/bug#5294
