For a long time there was this comment in SyncVar, which I followed up in the course of deprecation work by removing the method:
{code}
-  @deprecated("Will be removed in 2.8. SyncVar should not allow exception by design.")
-  def setWithCatch(x: => A) = synchronized {
-    try {
-      this set x
-    } catch {
-      case e =>
-        this setException e
-        throw e
-    }
-  }
-  
{code}
The fact that setException survived is an anomaly: if the comment can be believed, it too should be deleted.  I don't have any insight into the design motivations.
