Reported by Eugeniy D on scala-internals.

{code}
class C[@specialized(Double) A]()
class D[@specialized(Double) A]() {
    val (a, b) = (1, 2)
    val c = new C[A]()
}
{code}

Crashes the backend. In 2.12, GenBCode: {{unexpected type representation reached the backend: => Tuple2}}. In 2.11 during GenICode: {{error: Unknown type: => Tuple2, => Tuple2}}.


{code}
  <specialized> class D$mcD$sp extends D {
...
    <specialized> def <init>(): D$mcD$sp = {
      D$mcD$sp.super.<init>();
      D$mcD$sp.this.x$1 = {
        private[this] val x1: Tuple2 = (new Tuple2$mcII$sp(1, 2): Tuple2);
        case4(){
          if (D$mcD$sp.this.x1.ne(null))
...
{code}

when generating code for loading {{D$mcD$sp.this.x1}}, its {{sym.info}} is a {{NullaryMethodType}}. Note that this is in the specialized subclass {{D$mcD$sp}}, the class {{D}} also has a definition {{x1}} which seems to have a good type. Maybe a bug in duplicators? Just a guess.
description of duplicate SI-8320: "I narrowed it down to a `[@specialized(Double) T: ClassTag]` on a case class"
