(From [http://www.nabble.com/private-vals-in-traits--t4780372.html this mailing list thread])

Consider:
{code}
 trait A { val foo: String = "A" }
 trait B {
   private val foo: String = "B"
   def f = println(foo)
 }
 object Test extends Application with B with A {
   println(foo) // prints "A", as expected
   f            // prints "B", as expected
 }
{code}
This looks, good, but if I switch the order of B and A in the
declaration of Test, it doesn't compile, claiming that there's no such
value as foo.

Adriaan pointed out that this works in the interpreter, and I replied:

Interesting. I see now that it works in the interpreter (I hadn't
tried). But it does not work with scalac:
{code}
[~]% cat test.scala
trait A { val foo: String = "A" }
trait B {
   private val foo: String = "B"
   def f = println(foo)
}
object Test extends A with B {
   println(foo)
   f
}
[~]% scalac test.scala
test.scala:7: error: not found: value foo
   println(foo)
           ^
one error found
[~]% scalac -version
Scala compiler version 2.6.0-final -- (c) 2002-2007 LAMP/EPFL
[~]% scala
Welcome to Scala version 2.6.0-final.
Type in expressions to have them evaluated.
Type :help for more information.

scala> :load test.scala
Loading test.scala...
defined trait A
defined trait B
defined module Test

scala> Test
A
B
res0: Test.type = Test$$@7b37df
{code}

I would expect this to work in the compiler as it works in the interpreter. If this is _not_ a compiler defect, I would also expect it to fail in the interpreter. (The above session is with 2.6.0, but the behavior is the same in 2.6.1-RC1.)
(In r22482) Test case closes SI-261, no review.
I'm sorry, this bug still exists in 2.8 final. If you look carefully at the test case, you will see that it tests the wrong thing!

In the test case, the order of the _declarations_ of A and B are switched between the two versions:
{code}
trait A ...
trait B ...
{code} 
vs 
{code}
trait B ...
trait A ...
{code}

But this has *nothing* to do with the bug!! The important change is the order of A and B _in the declaration of Test_:
{{ 
object Test extends Application with A with B ... 
object Test extends Application with B with A ...  // this one fails!
{code}

In 2.8 final, it remains the case that this works correctly in the interpreter, and incorrectly in the compiler. There seems to be no change in behavior since the bug was opened. The original transcript I included when I opened the bug is still what I see with the new release.

Sorry to have to reopen this very old bug!


{{ 
object Test extends Application with A with B ...  // THIS one fails...
object Test extends Application with B with A ...
{code}

Sorry for all the confusion, it is actually the _first_ one ("A with B") which fails, as in the original bug. In the test case, both versions have "B with A".
See also slight variation in SI-7699 (marked as duplicate)
Yep!! Chalk up another three-digit bug for mr. Zaugg!

Verified to work with scalac from https://github.com/scala/scala/pull/3440. 
I'll submit a PR with the test case.

{code}
$ pr_dist 3440
$ /Users/adriaan/git/scala-dist/target/universal/stage/bin/scalac /Users/adriaan/Desktop/bugs/t261/Test.scala 
# WOOHOO
$ scalac -version
Scala compiler version 2.11.0-M7 -- Copyright 2002-2013, LAMP/EPFL
$ scalac /Users/adriaan/Desktop/bugs/t261/Test.scala:8: error: value foo in trait B cannot be accessed in object Test
     println(foo)
             ^
one error found

$ cat /Users/adriaan/Desktop/bugs/t261/Test.scala 
trait A { val foo: String = "A" }
trait B {
   private val foo: String = "B"
   def f = println(foo)
}
object Test extends A with B {
   def main(args: Array[String]) = {
     println(foo)
     f
   }
}

$ /Users/adriaan/git/scala-dist/target/universal/stage/bin/scala Test
A
B
{code}

PS: https://github.com/adriaanm/binfu/blob/master/scafu.sh#L41
