svetylk0 found out that
{code}
  try { "aaa".asInstanceOf[Int] } catch { case _ => "got it" }
{code} 
returns "aaa" instead of "got it" in Scala 2.8.1 and 2.9.0 trunk.

Scala 2.8.0 seems to have the right behavior.
(In r23965) In r22807 an optimization was added to remove Box(Unbox(x))
combinations.  It turns out that without this in place, an
expression like "x".asInstanceOf[Int] will no longer throw an
exception.  Refined the optimization.  Closes SI-4148, review by dragos.

https://github.com/scala/scala/commit/566fefb
