In PipedProcesses.runAndExitValue(), sink is waiting for Option[OutputStream] to be put to currentSink at line 132 of https://github.com/scala/scala/blob/2.11.x/src/library/scala/sys/process/ProcessImpl.scala#L132, but None will be put to currentSink at line 138 just after it, then sink may possibly do nothing when line 133-137 quickly passed. In this case, a Process's outputStream never to be closed, and a command reads data from STDIN like "wc" blocks forever.
I have written a patch for this problem include a test and making a pull request now.
This is related to SI-7350. See also the discussion in the PR for that ticket: https://github.com/scala/scala/pull/2379
I think both PR-2379 and PR-3906 didn't fix the leak of PipeSource and PipeSink discussed in  SI-7350. PipeSource.run() and PipeSink.run() are more complicated than they need to be. 

I suggest refactoring like this: 
{code}diff --git a/src/library/scala/sys/process/ProcessImpl.scala b/src/library/scala/sys/process/ProcessImpl.scala
index 2b7fcde..46d3df9 100644
--- a/src/library/scala/sys/process/ProcessImpl.scala
+++ b/src/library/scala/sys/process/ProcessImpl.scala
@@ -134,13 +134,15 @@ private[process] trait ProcessImpl {
       try {
         runInterruptible {
           val exit1 = first.exitValue()
-          currentSource put None
-          currentSink put None
           val exit2 = second.exitValue()
           // Since file redirection (e.g. #>) is implemented as a piped process,
           // we ignore its exit value so cmd #> file doesn't always return 0.
           if (b.hasExitValue) exit2 else exit1
         } {
+          currentSink put None
+          currentSource put None
+          sink.interrupt()
+          source.interrupt()
           first.destroy()
           second.destroy()
         }
@@ -175,14 +177,8 @@ private[process] trait ProcessImpl {
   ) extends PipeThread(false, () => label) {
 
     final override def run(): Unit = currentSource.get match {
-      case Some(source) =>
-        try runloop(source, pipe)
-        finally currentSource.unset()
-
-        run()
+      case Some(source) => runloop(source, pipe)
       case None =>
-        currentSource.unset()
-        BasicIO close pipe
     }
   }
   private[process] class PipeSink(
@@ -192,13 +188,8 @@ private[process] trait ProcessImpl {
   ) extends PipeThread(true, () => label) {
 
     final override def run(): Unit = currentSink.get match {
-      case Some(sink) =>
-        try runloop(pipe, sink)
-        finally currentSink.unset()
-
-        run()
+      case Some(sink) => runloop(pipe, sink)
       case None =>
-        currentSink.unset()
     }
   }
{code}
Sorry, I found that https://github.com/scala/scala/pull/3913 still have bugs PipeSource/PipeSink.release() block and BasicIO.transferFully doesn't catch InterruptedIOException. I'm writing for Tests for SI-7350.
This is also related to SI-7963. 

If a process is connected to stdin, even after the process exits, the reading thread is still around waiting for input. As soon as input is given, it unblocks and either realizes it has been interrupted, or just fails trying to write to a close stream. Since there is basically no way to have an interruptible stream on System.In, there isn't much we can do (except polling...)
I have not noticed problems reported in SI-7963, but I think it does not relate this. There is some problems in PipedProcesses as listed bellow:
- source and sink leak when b.run() fails at https://github.com/scala/scala/blob/538aa22ec8144430e778a34bc749eccb6f5dbf4c/src/library/scala/sys/process/ProcessImpl.scala#L132

- source, sink and second leak when a.run() fails at https://github.com/scala/scala/blob/538aa22ec8144430e778a34bc749eccb6f5dbf4c/src/library/scala/sys/process/ProcessImpl.scala#L133

- source and sink leak when Process.exitValue() interrupted in https://github.com/scala/scala/blob/538aa22ec8144430e778a34bc749eccb6f5dbf4c/src/library/scala/sys/process/ProcessImpl.scala#L135

- first and second do not properly connected when None putted to currentSink before sink receive Some(InputStream) in https://github.com/rubyu/scala/blob/538aa22ec8144430e778a34bc749eccb6f5dbf4c/src/library/scala/sys/process/ProcessImpl.scala#L138

I tried to fix these problems in https://github.com/scala/scala/pull/3913, but there was still a few bugs. I'm fixing it. 

And I have a question about BasicIO.transferFully.

- BasicIO.transferFullyImpl is a function copying data from InputStream to OutputStream. https://github.com/scala/scala/blob/538aa22ec8144430e778a34bc749eccb6f5dbf4c/src/library/scala/sys/process/BasicIO.scala#L223

- process.onInterrupt catches InterruptedException. https://github.com/scala/scala/blob/159baa268e5cc14b50bf29a40fff922e36dd7bc9/src/library/scala/sys/process/package.scala#L238

therefore it seems meaningless that BasicIO.transferFully using onInterrupt for catching a exception. I guess this originally intented to catch InterruptedIOException, and I suggest the correct implementation is:

{code}
      def onIOInterrupt[T](handler: => T): Throwable =?> T = {
        case _: InterruptedIOException => handler
      }
{code}

{code}
  def transferFully(in: InputStream, out: OutputStream): Unit =
    try transferFullyImpl(in, out)
    catch onIOInterrupt(())
{code}

Is this prediction not wrong?
I've added tests for SI-7350.
https://github.com/scala/scala/pull/3920
