```scala
class Foo(val bar : () => String);

class IP extends {
  val baz = "bar";
} with Foo(() => baz);

object Main extends Application{
  (new IP).bar();
}
```

Compiles fine. Trying to run Main will throw a VerifyError:

```scala
java.lang.VerifyError: (class: IP, method: <init> signature: ()V) Expecting to find object/array on stack
	at Main$$.<init>(error.scala:8)
	at Main$$.<clinit>(error.scala)
	at Main.main(error.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at scala.tools.nsc.ObjectRunner$$$$anonfun$$run$$1.apply(ObjectRunner.scala:75)
	at scala.tools.nsc.ObjectRunner$$.withContextClassLoader(ObjectRunner.scala:49)
	at scala.tools.nsc.ObjectRunner$$.run(ObjectRunner.scala:74)
	at scala.tools.nsc.MainGenericRunner$$.main(MainGenericRunner.scala:161)
	at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
```
The problem is that the anonymous function `() => baz` gets an unnecessary outer pointer, initialized in its constructor. And its constructor is called before the super constructor of the IP class:

```scala
IP.this.baz = baz$$1;
IP.super.this({
  (new IP$$$$anonfun$$$$init$$$$1(IP.this, baz$$1): Function0)
});
```

Either the anonfun should not get the useless outer pointer, or this code should be forbidden by the type checker.
Isn't the "useless reference to this" problem not already fixed in revision r15029 (in response to #854)? Does this work in head already?
